sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10.9"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
